Improve error output.

diff --git a/autoformat/java b/autoformat/java
--- a/autoformat/java
+++ b/autoformat/java
@@ -3,6 +3,6 @@
 d="$(cd "$(dirname "$0")"; pwd -P)/../tools/eclipse-java-formatter"
 
 "$d/ejf" "$1" || {
-  echo 'fatal: `ejf` failed for:' "$1" >&2
+  echo 'fatal: `ejf` (in ' "$d" ')  failed for:' "$1" >&2
   exit 1
 }
